### ISSUE TITLE
Common-lisp: computing relaive pathnames

### ISSUE THREAD

**Issue by Yehouda** [GrammaTech/gtirb#34]
in cl/gtirb.lisp it computes the path pf version.txt using a form that misses parts of the pathname. In prticular, in LispWorks for Windows the host has the driver letter, so it doesn't work without it. 
The right way to compute relative pathname is to use **asdf:system-relative-pathname**, i.e. to replace  the call **make-pathname** inside **defvar version.txt** by: 
 
`(asdf/system:system-relative-pathname "gtirb" "../version.txt")`.

The same apply to **\*gtirb-dir\*** in cl/test.lisp, which should be:

`(defvar *gtirb-dir* (asdf/system:system-relative-pathname  "gtirb" "../" ))
`

**Comment by eschulte** [comment]
Thanks for this!  I've just made the changes you suggested.
