### ISSUE TITLE
probably switched tokens: (defmethod :around is-equal-p-internal ((left t) (right t)) 

### ISSUE THREAD

**Issue by Yehouda** [GrammaTech/gtirb#35]
in cl/gtirb.lisp, there is a definition that starts (line 164):

`(defmethod :around is-equal-p-internal ((left t) (right t))`

That defines a method for tha **:around** generic function, with qualifier **is-equal-p-internal**. LispWorks errors on that. Presumably the tokens are swicthed, and it should be:

`(defmethod is-equal-p-internal  :around ((left t) (right t))`

**Comment by eschulte** [comment]
Thanks again!
