### ISSUE TITLE
build unsuccessful

### ISSUE THREAD

**Issue by aman30865** [GrammaTech/gtirb#37]
<pre>[100%] Built target googletest
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found suitable version "3.12.3", minimum required is "3.0.0") 
-- clang-tidy not found.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at doc/python/CMakeLists.txt:30 (message):
  sphinx-apidoc was not found.  HTML documentation for the Python API will
  not be generated.

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8.11")
APIs to be built:
    C++     ON
    Python  ON
    Lisp    OFF
    Java    OFF
-- Configuring incomplete, errors occurred!
See also "/build/CMakeFiles/CMakeOutput.log".
See also "/build/CMakeFiles/CMakeError.log".
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/gtirb
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googlemock
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/googletest-src/googletest
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/proto
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/gtirb/proto
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/src/test/testInputBinary
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/python
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/cpp
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/python
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/examples
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
   used as include directory in directory /build/gtirb/doc/general
</pre>
wasn't getting this error earlier. But now when I tried to make a fresh build its showing this error.

**Comment by aman30865** [comment]
Following code gave the above error:
cd build &&  git clone https://github.com/GrammaTech/ddisasm.git &&  cmake gtirb

**Comment by AaronBallman** [comment]
Can you paste the full cmake invocation and output?
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
```
It sounds a bit like CMake isn't able to find boost, but if that were the case, I'd expect CMake to error in a somewhat different way.

**Comment by iconmaster5326** [comment]
What version of Boost do you have? How did you install it?

**Comment by aruncgowda** [comment]
Make Warning at CMakeLists.txt:122 (message):
  Lisp interpreter not found; disabling building of Lisp API.

  If this is in error, try giving -DLISP=...  to CMake to specify what
  program to use.


-- Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Development) (Required is at least version "1.8.0")
CMake Warning at CMakeLists.txt:155 (message):
  Java 8 compiler not found; disabling building of Java API.

  If this is in error, try setting the environment variable $JAVA_HOME.


CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.67 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:290 (find_package)


-- Configuring done
-- Generating done
-- Build files have been written to: /home/arun/build/googletest-download
[ 11%] Performing update step for 'googletest'
[ 22%] No configure step for 'googletest'
[ 33%] No build step for 'googletest'
[ 44%] No install step for 'googletest'
[ 55%] No test step for 'googletest'
[ 66%] Completed 'googletest'
[100%] Built target googletest
-- clang-tidy not found.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
CMake Warning at doc/python/CMakeLists.txt:30 (message):
  sphinx-apidoc was not found.  HTML documentation for the Python API will
  not be generated.


-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.8.11")
APIs to be built:
    C++     ON
    Python  ON
    Lisp    OFF
    Java    OFF
-- Configuring incomplete, errors occurred!
See also "/home/arun/build/CMakeFiles/CMakeOutput.log".
See also "/home/arun/build/CMakeFiles/CMakeError.log".

@AaronBallman @iconmaster5326 
i am facing same problem please can u give solutions

**Comment by AaronBallman** [comment]
> @AaronBallman @iconmaster5326
> i am facing same problem please can u give solutions

I think your issue is a bit different from the OP's. Your issue is that the version of boost you have installed is too old: `Detected version of Boost is too old. Requested version was 1.67 (or newer).`

Please try installing an updated Boost to see if it resolves your issue.

**Comment by aruncgowda** [comment]
@AaronBallman 
Thank u sir i built it successfully

i updated boost and then error was gone
