### ISSUE TITLE
VARINT:LENGTH32 not found - can't build

### ISSUE THREAD

**Issue by quicklisp** [GrammaTech/gtirb#39]
Log here: http://report.quicklisp.org/2020-09-15/failure-report/gtirb.html#proto

I get this:

```
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE: Symbol "LENGTH32" not found in the VARINT package.
```

**Comment by brown** [comment]
Zach is building Quicklisp using a release of gtirb from March that has generated protobuf code checked in.  Those files are no longer compatible with the support code in the protobuf package.  The right fix I think is to update the gtirb branch that Quicklisp distributes to something more recent.

**Comment by eschulte** [comment]
I just updated the Quicklisp branch with regenerated lisp files using the latest version of the protobuf package.  Hopefully this fixes this issue.  Thanks for the report and for the diagnosis.

**Comment by eschulte** [comment]
I believe this is fixed so I'm going to close this issue, but please reopen if I'm wrong here.  Thanks
