### ISSUE TITLE
IR issues

### ISSUE THREAD

**Issue by aruncgowda** [GrammaTech/gtirb#41]
@AaronBallman  hello, 
I have one small issue , how to open generated IR?
If any one has gtirb commands please share

a@a-VirtualBox:~$ gtirb-pprinter --ir helloworld
[INFO]  Reading GTIRB file:     "helloworld"
[ERROR] Failed to load the GTIRB data from the file.

i am getting this error

**Comment by jdorn-gt** [comment]
That error message usually indicates that the file named "helloworld" does not contain GTIRB data or that the GTIRB data has been corrupted.

Could you share some more information about how you generated the IR? For example, did you use ddisasm or some other tool?

**Comment by eschulte** [comment]
I'm closing this issue, please reopen if there is still a problem or if more assistance is needed.  Thanks
