### ISSUE TITLE
About FunctionNames Aux data

### ISSUE THREAD

**Issue by tearosccebe** [GrammaTech/gtirb#47]
In ddisasm's readme. FunctionNames are a std::map<gtirb::UUID, std::string>
functionNames | std::map<gtirb::UUID, std::string> | The name of each function.

However, in the gtirb source, it is std::map<gtirb::UUID,gtirb::UUID>. why?

**Comment by eschulte** [comment]
Ah, thanks for pointing this out!  This is a mistake in the DDisasm README which we'll have to fix.  The `functionNames` table does have type `std:map<UUID, UUID>` where the second UUID points to a symbol whose `name` is the actual string function name.  E.g., in the Python API:
```python
>>> ir = gtirb.IR.load_protobuf("hello.gtirb")
>>> list(ir.modules[0].aux_data["functionNames"].data.items())[0]
(UUID('03d6d218-7d2d-4353-b18b-5f90d03730c9'), Symbol(uuid=UUID('dc36ae79-811c-48c9-aaa5-c076d9c0cca4'), name='frame_dummy', payload=CodeBlock(uuid=UUID('c24cfd7d-5faa-4c18-9013-b29b60b0c8a9'), size=6, offset=224, decode_mode=0, ), at_end=False, ))
>>> list(ir.modules[0].aux_data["functionNames"].data.items())[0][1]
Symbol(uuid=UUID('dc36ae79-811c-48c9-aaa5-c076d9c0cca4'), name='frame_dummy', payload=CodeBlock(uuid=UUID('c24cfd7d-5faa-4c18-9013-b29b60b0c8a9'), size=6, offset=224, decode_mode=0, ), at_end=False, )
>>> list(ir.modules[0].aux_data["functionNames"].data.items())[0][1].name
'frame_dummy'
```

**Comment by eschulte** [comment]
I'm closing this issue as we have now fixed the typo in the DDisasm README.  Please reopen or open a new issue if any questions remain.  Thanks!
