### ISSUE TITLE
How to reference APIs from PEImportSymbols from FunctionEntries or CFG?

### ISSUE THREAD

**Issue by tearosccebe** [GrammaTech/gtirb#48]
FunctionEntry does not have any reference to PEImportSymbols, How could I know what APIs calling to DLLs from the IR?

**Comment by tjohnson-gt** [comment]
Yes, the FunctionEntry AuxData table only covers functions that are present directly in the binary.

I'm not sure I understand your question though. The PEImportSymbols table includes a UUID to the Symbol being imported. This *is* the API being called. If you're asking about how to find where a call to such an API might be in the CFG, typically those are modeled as ProxyBlocks in the CFG. You should be able to find a ProxyBlock by getting the referent of the corresponding Symbol.

Note: There *is* in some cases a translation phase for imported symbols that goes through the SymbolForwarding AuxData table. I forget exactly how that works, but you may have to convert from one Symbol to another Symbol through this table to find the ProxyBlock.

**Comment by swang206** [comment]
> Yes, the FunctionEntry AuxData table only covers functions that are present directly in the binary.
> 
> I'm not sure I understand your question though. The PEImportSymbols table includes a UUID to the Symbol being imported. This _is_ the API being called. If you're asking about how to find where a call to such an API might be in the CFG, typically those are modeled as ProxyBlocks in the CFG. You should be able to find a ProxyBlock by getting the referent of the corresponding Symbol.
> 
> Note: There _is_ in some cases a translation phase for imported symbols that goes through the SymbolForwarding AuxData table. I forget exactly how that works, but you may have to convert from one Symbol to another Symbol through this table to find the ProxyBlock.

1. But I do not find where __imp_ apis from windows DLLs in FunctionEntries. How to get that?
2. Another question is that I try to directly modify the CodeBlock::rawBytes() by filling zero or other characters to that trunk to block the function. However, after I modified it, the ddisasm can no longer generate assembly from that IR. It falls to an infinite loop. Why?

**Comment by eschulte** [comment]
> Another question is that I try to directly modify the CodeBlock::rawBytes() by filling zero or other characters to that trunk to block the function. However, after I modified it, the ddisasm can no longer generate assembly from that IR. It falls to an infinite loop. Why?

The bytes of a code block should be valid machine code bytes.  When you go to generate a new binary gtirb-pprinter will try to interpret these bytes as instructions to print an assembly file that is then assembled and linked.  If you want to rewrite a code block to make it unusable I'd suggest you overwrite it with `hlt` instructions or maybe even better you could delete the code block from the GTIRB entirely.  You might also want to look at using [gtirb-rewriting](https://github.com/grammatech/gtirb-rewriting) to help in the modification of code blocks.

**Comment by swang206** [comment]
> > Another question is that I try to directly modify the CodeBlock::rawBytes() by filling zero or other characters to that trunk to block the function. However, after I modified it, the ddisasm can no longer generate assembly from that IR. It falls to an infinite loop. Why?
> 
> The bytes of a code block should be valid machine code bytes. When you go to generate a new binary gtirb-pprinter will try to interpret these bytes as instructions to print an assembly file that is then assembled and linked. If you want to rewrite a code block to make it unusable I'd suggest you overwrite it with `hlt` instructions or maybe even better you could delete the code block from the GTIRB entirely. You might also want to look at using [gtirb-rewriting](https://github.com/grammatech/gtirb-rewriting) to help in the modification of code blocks.

Thank you for your reply.

Any example of C++ that can remove codeblock? Can I just remove it from the CFG with boost graph apis?

**Comment by tjohnson-gt** [comment]
Regarding the __imp_ symbols, you will not find them in the FunctionEntries table because they do not refer to functions present in the local file at all. An __imp_ symbol is merely a label associated with an import table entry - a memory slot that holds an address populated at dynamic link time. There's no function present in the executable file that the symbol attaches to. If you're interested in looking at such functions, you need to analyze the DLL that contains them.

**Comment by tjohnson-gt** [comment]
Regarding C++ code for removing CodeBlocks: You should remove it from the CFG, yes, but you should also remove the CodeBlock from the ByteInterval that contains it. You will likely also need to update the code bytes in any CodeBlock that might jump to the block you're removing, so you don't have a dangling jump/call to it once it's removed.

I don't know of any sample code for doing this in C++. Most folks doing rewriting with GTIRB I think use the Python API for doing the rewriting.

**Comment by swang206** [comment]
> Regarding C++ code for removing CodeBlocks: You should remove it from the CFG, yes, but you should also remove the CodeBlock from the ByteInterval that contains it. You will likely also need to update the code bytes in any CodeBlock that might jump to the block you're removing, so you don't have a dangling jump/call to it once it's removed.
> 
> I don't know of any sample code for doing this in C++. Most folks doing rewriting with GTIRB I think use the Python API for doing the rewriting.

Another question. Does CFG correctly track function pointers and vtables?

**Comment by eschulte** [comment]
I'm closing this because I believe all questions have been answered, but please reopen if anything lingers.
