### ISSUE TITLE
Does gtirb support stack remodeling?

### ISSUE THREAD

**Issue by swang206** [GrammaTech/gtirb#50]
I would like to trace data from the stack memory with static analysis. Does gtirb support that? If it does not, what else I could look at?

**Comment by tjohnson-gt** [comment]
Sorry, but GTIRB does not include modeling of the stack layout at this time. I'm also not aware of anything that's publicly available that would perform the necessary analysis to identify the variables on the stack in a GTIRB context.

You are certainly welcome to put together your own analysis and attach the resulting information as a new AuxData table to your GTIRB files. If you decide to do this, we'd be happy to share the schema we use internally at GrammaTech for the AuxData. Just let us know if you'd find that useful.
