### ISSUE TITLE
Value Set Analysis on GTIRB

### ISSUE THREAD

**Issue by SaiVK** [GrammaTech/gtirb#53]
Hello Everyone
   Is there any inbuilt Value Set Analysis implementation available for GTIRB? If yes can anyone point me to the repo? If not, is it possible for making use of Angr's analysis tools to work on GTIRB?

Thanking you
Sai

**Comment by tjohnson-gt** [comment]
Unfortunately, we do not have any existing support for VSA in the GTIRB context at this time. We're also not aware of any work to interface between GTIRB and Angr.

That said, you are more than welcome to develop your own interface between the two tools if you feel motivated enough. Both are open source, so it should be reasonably feasible.

**Comment by SaiVK** [comment]
Thank you @tjohnson-gt.
