### ISSUE TITLE
can't build gtirb

### ISSUE THREAD

**Issue by dhucul** [GrammaTech/gtirb#54]
make[2]: *** [googletest-build/googletest/CMakeFiles/gtest.dir/build.make:82: googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:504: googletest-build/googletest/CMakeFiles/gtest.dir/all] Error 2
gmake: *** [Makefile:182: all] Error 2

Cant figure out how to solve this. NO specific information.

**Comment by tjohnson-gt** [comment]
Is there absolutely nothing in the log before this that looks fishy? Even if you don't see anything odd, you should post the full log, as *we* may see something odd that you're not picking up on.

The issue appears to be something to do with googletest. It could also be something about how gtirb's build system is building googletest or how gtirb's unit testing is interfacing with it. Or it could be some problem just in googletest.
