### ISSUE TITLE
vscode extension available

### ISSUE THREAD

**Issue by ucasqsl** [GrammaTech/gtirb#55]
I saw the gtirb vscode extension at https://grammatech.github.io/prj/gtirb-vscode/. That's pretty cool! When will this work be available to us?

**Comment by eschulte** [comment]
Hi @ucasqsl, thanks for asking and I'm happy you liked the demo!

There are components that enable the gtirb-vscode integration that are not open-source.  We are not yet sure if and how we are going to release these components and/or gtirb-vscode as a whole.  This is an active topic of discussion.  I'll follow up in this thread as we formulate a plan here.

Can I ask, how would you anticipate using this if it were available?

**Comment by ucasqsl** [comment]
I'm trying to write some analysis base on ddisasm's result. It would be very convenient to have a tool like this to visualize the Auxdata generated by the analysis. Also, I think I can use it to do binary rewriting when solving CTF challenges.

**Comment by eschulte** [comment]
This is now available as open-source software at https://github.com/grammatech/gtirb-vscode.  It has not received much (or any) external use yet, so please let us know if you run into any issues getting it working locally and we'll help troubleshoot and improve our installation instructions.
