### ISSUE TITLE
Third-party packages

### ISSUE THREAD

**Issue by AaronBallman** [GrammaTech/gtirb#8]
We currently download some third-party packages automatically for the user (googletest and gsl). This is a nice thing when getting started on the project as it makes it easier to get the source code, compile, and start playing with it. However, in places where this can touch the API, it introduces potential problems where the end user's project is using GSL and we download an ABI-incompatible version internally and use it. We have interfaces like `ByteMap::setData()` that work with GSL interfaces and this would cause hard to understand compile errors in the best case, or silent ODR violations and subtly broken code at runtime in the worst case.

We should figure out whether these are prerequisites for the project (so the user is responsible for supplying them) or implementation details for the project (so the user is generally unaware of their presence and we can download them ourselves). For instance, we may decide to download these only if they're not already present on the system (with some version checks?), never download them and only enable the feature if they're present (such as disable building tests if googletest cannot be found), or some other approach.

**Comment by AaronBallman** [comment]
Another detail we will want to keep in mind is repeatability of builds. We've had issues where the automatic download of, for instance, gtest, breaks our CI pipeline because of changes to the third-party library that we were not prepared to take on. In one case, gtest deprecated an API that we were using and our -Werror build failed because of new deprecation warnings.

This sort of thing might (maybe, but I'm not convinced still) be reasonable for internal developers, but seems like it has the potential to cause significant pain for out-of-tree users.

**Comment by iconmaster5326** [comment]
Since this issue has been posted, we now remove auto-downloading for everything but Google Test, which Google itself recommends we download for the user. Does this resolve this issue?

**Comment by AaronBallman** [comment]
It's resolved to my satisfaction, thank you for reminding me!
